### ISSUE TITLE
help needed

### ISSUE THREAD

**Issue by yuliaa00** [Inplex-sys/proxy-list#2]
Hii🙋🏻‍♀️

Do you perhaps have some time to help me out?

**Comment by Inplex-sys** [comment]
Helping you for what ?

**Comment by yuliaa00** [comment]
do you have telegram or discord

**Comment by Inplex-sys** [comment]
what do you need help with?

**Comment by yuliaa00** [comment]
i need some HQ proxies

**Comment by Inplex-sys** [comment]
i don't have HQ proxy
